name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: codeberg-medium
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install JDK 21
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-21-jdk curl
          java -version

      - name: Setup sbt (sbt-extras)
        run: |
          curl -sL https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt -o sbt
          chmod +x sbt
          ./sbt --version

      - name: Run tests
        env:
          JAVA_HOME: /usr/lib/jvm/java-21-openjdk-amd64
        run: |
          ./sbt --batch coreJVM/test cliJVM/test
