version: '3'

services:
  chester-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - JAVA_HOME=/opt/graalvm 